<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('databanks')->insert([
            [
                'titre' => 'Action Contre la Faim (Humanitaire)',
                'slug' => 'acfs',
                'description' => 'Organisation humanitaire engagée dans la lutte contre la faim.',
                'criteres' => 'Critères ACF',
                'source' => 'Source ACF',
                'budget' => 1000000,
                'nom_contact' => 'Jean Dupont',
                'email_contact' => '+221123456789',
                'prescripteur_id' => 1,
                'pays_partner_id' => 1,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Ministère de l\'Elevage et de la Production Animale (Elevage)',
                'slug' => 'meppa',
                'description' => 'Ministère chargé de l\'élevage et de la production animale.',
                'criteres' => 'Critères MEPA',
                'source' => 'Source MEPA',
                'budget' => 2000000,
                'nom_contact' => 'Marie Ndiaye',
                'email_contact' => '+221987654321',
                'prescripteur_id' => 2,
                'pays_partner_id' => 2,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Agence Nationale de la Statistique et de la Démographie (Statistiques)',
                'slug' => 'ansd',
                'description' => 'Agence nationale chargée des statistiques et de la démographie.',
                'criteres' => 'Critères ANSD',
                'source' => 'Source ANSD',
                'budget' => 1500000,
                'nom_contact' => 'Aissatou Sow',
                'email_contact' => '+221345678901',
                'prescripteur_id' => 3,
                'pays_partner_id' => 3,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Centre de Suivi Ecologique (Gestion des Ressources Naturelles)',
                'slug' => 'cse',
                'description' => 'Centre dédié à la gestion des ressources naturelles.',
                'criteres' => 'Critères CSE',
                'source' => 'Source CSE',
                'budget' => 1200000,
                'nom_contact' => 'Boubacar Diop',
                'email_contact' => '+221456789012',
                'prescripteur_id' => 4,
                'pays_partner_id' => 4,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Commissariat à la Sécurité Alimentaire (Stocks Alimentaires)',
                'slug' => 'csa',
                'description' => 'Commission en charge de la gestion des stocks alimentaires.',
                'criteres' => 'Critères CSA',
                'source' => 'Source CSA',
                'budget' => 1800000,
                'nom_contact' => 'Fatou Bâ',
                'email_contact' => '+221567890123',
                'prescripteur_id' => 5,
                'pays_partner_id' => 5,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Direction de l’Horticulture (Agriculture)',
                'slug' => 'dhort',
                'description' => 'Direction responsable de l’horticulture.',
                'criteres' => 'Critères DHORT',
                'source' => 'Source DHORT',
                'budget' => 1100000,
                'nom_contact' => 'Ousmane Thiam',
                'email_contact' => '+221678901234',
                'prescripteur_id' => 6,
                'pays_partner_id' => 6,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Direction de la Protection des Végétaux (Agriculture)',
                'slug' => 'dpv',
                'description' => 'Direction en charge de la protection des végétaux.',
                'criteres' => 'Critères DPV',
                'source' => 'Source DPV',
                'budget' => 1300000,
                'nom_contact' => 'Mariama Ba',
                'email_contact' => '+221789012345',
                'prescripteur_id' => 7,
                'pays_partner_id' => 7,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Direction de l\'Analyse, de la Prévision et des Statistiques Agricoles (Statistiques Agricoles)',
                'slug' => 'dapsa',
                'description' => 'Direction dédiée aux statistiques agricoles.',
                'criteres' => 'Critères DAPSA',
                'source' => 'Source DAPSA',
                'budget' => 1400000,
                'nom_contact' => 'Seydou Diallo',
                'email_contact' => '+221890123456',
                'prescripteur_id' => 8,
                'pays_partner_id' => 8,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Direction de L\'Equité de l\'Egalité du Genre (Social)',
                'slug' => 'deeg',
                'description' => 'Direction responsable de l’équité et de l’égalité du genre.',
                'criteres' => 'Critères DEEG',
                'source' => 'Source DEEG',
                'budget' => 900000,
                'nom_contact' => 'Khadim Gueye',
                'email_contact' => '+221901234567',
                'prescripteur_id' => 9,
                'pays_partner_id' => 9,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Direction des Eaux et Forêts, Chasses et Conservation des Sols (Eaux et Forêts)',
                'slug' => 'defccs',
                'description' => 'Direction en charge des eaux, des forêts et de la conservation des sols.',
                'criteres' => 'Critères DEFCCS',
                'source' => 'Source DEFCCS',
                'budget' => 1600000,
                'nom_contact' => 'Aissatou Diouf',
                'email_contact' => '+221012345678',
                'prescripteur_id' => 10,
                'pays_partner_id' => 10,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Division de l\'Alimentation et de la Nutrition (Sécurité Alimentaire)',
                'slug' => 'dan',
                'description' => 'Division chargée de l’alimentation et de la nutrition.',
                'criteres' => 'Critères DAN',
                'source' => 'Source DAN',
                'budget' => 1100000,
                'nom_contact' => 'Oumar Sarr',
                'email_contact' => '+221123456788',
                'prescripteur_id' => 11,
                'pays_partner_id' => 11,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Division du Système d\'Information Sanitaire et Sociale (Social)',
                'slug' => 'dsiss',
                'description' => 'Division responsable du système d’information sanitaire et sociale.',
                'criteres' => 'Critères DSISS',
                'source' => 'Source DSISS',
                'budget' => 1000000,
                'nom_contact' => 'Marieme Faye',
                'email_contact' => '+221234567890',
                'prescripteur_id' => 12,
                'pays_partner_id' => 12,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Division Régionale de l\'Hydraulique (Eau)',
                'slug' => 'drh',
                'description' => 'Division en charge de l’hydraulique régionale.',
                'criteres' => 'Critères DRH',
                'source' => 'Source DRH',
                'budget' => 1300000,
                'nom_contact' => 'Ibrahima Sow',
                'email_contact' => '+221345678912',
                'prescripteur_id' => 13,
                'pays_partner_id' => 13,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Laboratoire de Recherche en Nutrition et Alimentation Humaine (Nutrition)',
                'slug' => 'larnah',
                'description' => 'Laboratoire spécialisé dans la recherche en nutrition.',
                'criteres' => 'Critères LARNAH',
                'source' => 'Source LARNAH',
                'budget' => 1100000,
                'nom_contact' => 'Adama Keita',
                'email_contact' => '+221456789013',
                'prescripteur_id' => 14,
                'pays_partner_id' => 14,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Secrétariat Exécutif Conseil National à la Sécurité Alimentaire (Sécurité Alimentaire et Résilience)',
                'slug' => 'se-cnsa',
                'description' => 'Secrétariat chargé de la sécurité alimentaire et de la résilience.',
                'criteres' => 'Critères SE-CNSA',
                'source' => 'Source SE-CNSA',
                'budget' => 1200000,
                'nom_contact' => 'Aissatou Fall',
                'email_contact' => '+221567890234',
                'prescripteur_id' => 15,
                'pays_partner_id' => 15,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Secrétariat Exécutif Conseil National de Développement de la Nutrition (Nutrition)',
                'slug' => 'se-cndn',
                'description' => 'Secrétariat chargé du développement de la nutrition.',
                'criteres' => 'Critères SE-CNDN',
                'source' => 'Source SE-CNDN',
                'budget' => 1400000,
                'nom_contact' => 'Sokhna Diagne',
                'email_contact' => '+221678901345',
                'prescripteur_id' => 16,
                'pays_partner_id' => 16,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'titre' => 'Service Régional des Pêches et de la Surveillance (Pêche)',
                'slug' => 'srps',
                'description' => 'Service régional dédié à la pêche et à la surveillance.',
                'criteres' => 'Critères SRPS',
                'source' => 'Source SRPS',
                'budget' => 1100000,
                'nom_contact' => 'Cheikh Ndiaye',
                'email_contact' => '+221789012346',
                'prescripteur_id' => 17,
                'pays_partner_id' => 17,
                'locked_by' => null,
                'locked_at' => null,
                'started_at' => now(),
                'deadline_question' => now()->addDays(30),
                'deadline' => now()->addDays(60),
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ]);
    }
}
